[package]
name = "grad"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
confy = "0.6.1"
evalexpr = "12.0.2"
flate2 = "1.1.1"
macroquad = "0.4.14"
rand = "0.9.1"
serde = "1.0.219"
serde_derive = "1.0.219"
